### ISSUE TITLE
How to get it working in ec2?

### ISSUE THREAD

**Issue by 123-rj** [varunshenoy/opendream#58]
I am beginner in this AI world, trying to get this UI running in ec2 instance but having some difficulties getting it to work. I have managed to launch the UI using `sh run_opendream.sh` and get the UI loading in port 3000. However, I cannot get anything else working other than loading the UI. Here is the error shot from the inspect element, it seems to point something at port 8000. How do I get this working in ec2?

![image](https://github.com/varunshenoy/opendream/assets/126132996/748fc0d1-df67-47b3-ae11-83353c8c9fca)

**Comment by 123-rj** [comment]
FYI, manage to solve this after tinkering with the codes for a good while. Change all the 127.xx.xx.xx:8000 to ec2-public-ip:8000. There are about 3 or 4 scripts that require these editing. Also change the  `allow_origins=origins` to  `allow_origins=["*"]` at the `server.py`. Finally, when running the server, need to specify the --host and --port values.

**Comment by varunshenoy** [comment]
Thank you for sharing these steps!
